### ISSUE TITLE
Lazy initialisation of lexicons can cause ConcurrentModificationException

### ISSUE THREAD

**Issue by Craigacp** [factorie/factorie#229]
It's possible to get this kind of stack trace out of the lexicon annotation method.
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
        at java.util.HashMap$KeyIterator.next(HashMap.java:956)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at cc.factorie.app.nlp.lexicon.TrieNode.cc$factorie$app$nlp$lexicon$TrieNode$$updateEmitDepth(TrieNode.scala:184)
        at cc.factorie.app.nlp.lexicon.TrieNode$.setFailureTransitions(TrieNode.scala:246)
        at cc.factorie.app.nlp.lexicon.AhoCorasick.setTransitions(AhoCorasick.scala:189)
        at cc.factorie.app.nlp.lexicon.AhoCorasick.lemmatizeAndTagMentions(AhoCorasick.scala:144)

It occurs when there are multiple threads using the same NER model, without the model being executed in a single thread beforehand. This is because the lexicon construction code isn't thread safe, and I'd assumed the lazy val construction of the lexicon objects would stop accesses before the single thread had finished construction. It appears the models themselves are thread safe, after the lexicons have been constructed.

I'm working on a fix for this by annotating a few methods with synchronised, which should be done once I've tested it doesn't slow things down too much. I'm just raising this issue so people know it's currently a problem in mult-threaded environments.

**Comment by strubell** [comment]
Did you ever get around to coding up a fix for this? If not, we'd like to look in to it, do you have any pointers (e.g. what needs to be synchronized).

**Comment by Craigacp** [comment]
I covered everything with synchronized to prevent other multithreading issues as you really only want a single thread in the constructor, but I can't guarantee it's fixed. In the end I made an initialize lexicon method on StackedChainNER and made that called by a single thread before I did any multi-threaded computation. I'll push the synchronized in when the contributors agreement is in place as it's tangled up in the work I did to halve the lexicon memory footprint.

**Comment by strubell** [comment]
Great, thanks Adam, sounds good! Any idea how soon that might be?

**Comment by Craigacp** [comment]
Unfortunately not. Much closer than the last time it came up. I believe everything is approved in concept, just waiting on a few tiny details.

**Comment by strubell** [comment]
Workaround in PR #276
