### ISSUE TITLE
LoopyBeliefPropagation may not work with varying number of variables

### ISSUE THREAD

**Issue by binh-vu** [factorie/factorie#387]
Hi,

When I try to define a factor template that have varying number of neighbors, I got this error

```
Exception in thread "main" java.lang.ClassCastException: cc.factorie.variable.SeqVariable cannot be cast to cc.factorie.variable.VectorVar
	at cc.factorie.infer.BPFactor1Factor2.<init>(BP.scala:222)
	at cc.factorie.infer.BPFactorFactory$.newBPFactor(BP.scala:46)
	at cc.factorie.infer.LoopyBPSummary$$anonfun$apply$2.apply(BP.scala:511)
	at cc.factorie.infer.LoopyBPSummary$$anonfun$apply$2.apply(BP.scala:511)
	at scala.collection.mutable.LinkedHashSet.foreach(LinkedHashSet.scala:93)
	at cc.factorie.infer.LoopyBPSummary$.apply(BP.scala:511)
	at cc.factorie.infer.InferByBPLoopy$.infer(BP.scala:814)
	at cc.factorie.infer.InferByBPLoopy$.infer(BP.scala:810)
	at cc.factorie.optimize.LikelihoodExample.accumulateValueAndGradient(Example.scala:113)
	at cc.factorie.optimize.BatchTrainer$$anonfun$processExamples$1.apply(Trainer.scala:55)
	at cc.factorie.optimize.BatchTrainer$$anonfun$processExamples$1.apply(Trainer.scala:55)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at cc.factorie.optimize.BatchTrainer.processExamples(Trainer.scala:55)
	at cc.factorie.optimize.Trainer$.train(Trainer.scala:406)
	at cc.factorie.optimize.Trainer$.batchTrain(Trainer.scala:441)
```

This is my template
```
new DotTemplate2[TripleLabel, SeqVariable[TripleLabel]]{
  factorName = "SubStructure"
  val nFeature = 1
  val weights: Weights1 = Weights(new DenseTensor1(nFeature))

  def unroll1(label: TripleLabel): Iterable[Factor] = {
    if (label.triple.childrenLabel.isEmpty) Nil
    else Factor(label, new SeqVariable(label.triple.childrenLabel))
  }
  def unroll2(children: SeqVariable[TripleLabel]) = throw new Exception("Should not call this")

  override def statistics(v1: BooleanValue, v2: IndexedSeq[TripleLabel]): Tensor = {
    // return feature here
    val allChildrenIsWrong = if (v2.forall(_.booleanValue == false)) 1.0 else 0.0
    new DenseTensor1(Array(allChildrenIsWrong))
  }
}
```

I have tried VarArg instead of SeqVariable but still have this error. I take a look the code at `cc.factorie.infer.BP.scala` line 44-49

```
      case factor:Factor2[DiscreteVar @unchecked,DiscreteVar @unchecked] =>
        if (varying.contains(factor._1) && varying.contains(factor._2)) new BPFactor2Factor2(factor, new BPEdge(summary.bpVariable(factor._1)), new BPEdge(summary.bpVariable(factor._2)), summary, summary.ring)
        else if (varying.contains(factor._1)) new BPFactor1Factor2(factor.asInstanceOf[Factor2[DiscreteVar,VectorVar]], new BPEdge(summary.bpVariable(factor._1)), summary)
        else if (factor._1.isInstanceOf[DiscreteVar]) new BPFactor1Factor2(factor.asInstanceOf[Factor2[DiscreteVar,VectorVar]], new BPEdge(summary.bpVariable(factor._2)), summary)
        else new BPFactor1Factor2Left(factor.asInstanceOf[Factor2[VectorVar,DiscreteVar]], new BPEdge(summary.bpVariable(factor._2)), summary)
```

It seems that even if I make a sub-class contains all varying neighbors and inherit VectorVar, the code here will treat the second variable of a factor as constant, and won't update the value properly.

Can you please show me the correct way to work though this issue? Any help would be greatly appreciated!

**Comment by lvilnis** [comment]
I don't believe belief propagation inference supports variable-neighbored (or frankly even fixed 3- or 4-neighbored) factors right now. 

So this is a (very reasonable) feature request. In the meantime you could try one of the other inference methods like MCMC (including Gibbs), iterated conditional modes, MPLP? 

Discrete mean field doesn't support >2 neighbors but it would be quite easy to extend to your case, much easier than BP. 

Sorry for the unsatisfying answer, patches are definitely welcome!

**Comment by binh-vu** [comment]
Got it. Thank you very much.
